# -*- coding: utf-8 -*-
"""TEMPLATE UPLOAD ASTRI-STELLA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBDYD7ljncG7gqlhYhVfa5WxZwoaQpQp
"""

# 1. Install library yang dibutuhkan
!pip install gdown openpyxl -q

import openpyxl
import gdown
from google.colab import files
import os

# ==========================================
# 1. Download TEMPLATE dari Google Drive
# ==========================================
print("Mengunduh TEMPLATE UPLOAD ASTRI-STELLA dari Google Drive...")
file_id = '1SV5YYaIRsubz-6nsin5F-6yWj64-Ljjn'
gdrive_url = f'https://drive.google.com/uc?id={file_id}'
template_file = "TEMPLATE UPLOAD ASTRI - STELLA.xlsx"

# Proses download file template (jika belum ada di session)
if not os.path.exists(template_file):
    gdown.download(gdrive_url, template_file, quiet=False)

# ==========================================
# 2. Upload Data Awal (HPDB)
# ==========================================
print("\n" + "="*50)
print("Silakan upload 1 file Excel data awal Anda (bisa berisi banyak sheet).")
print("="*50)
uploaded = files.upload()

# Mengambil nama file yang baru saja diunggah
source_file = list(uploaded.keys())[0]

print("\nMemulai proses pemetaan data...")

try:
    # Memuat workbook sumber
    wb_source = openpyxl.load_workbook(source_file, data_only=True)

    # Mengambil semua nama sheet yang ada di dalam file sumber
    sheet_names = wb_source.sheetnames
    print(f"\nDitemukan {len(sheet_names)} sheet dalam file sumber: {sheet_names}\n")

    # ==========================================
    # 3. Looping untuk setiap Sheet
    # ==========================================
    for sheet_name in sheet_names:
        print(f"--- Memproses sheet: '{sheet_name}' ---")
        ws_source = wb_source[sheet_name]

        # Memuat workbook template BARU untuk setiap sheet agar datanya tidak bertumpuk
        wb_temp = openpyxl.load_workbook(template_file)
        ws_temp = wb_temp["CLUSTER"]

        # ------------------------------------------
        # PEMETAAN 1 & 2: Pemetaan Sel Tunggal
        # ------------------------------------------
        ws_temp["A2"] = ws_source["Y10"].value

        ws_temp["B2"] = ws_source["AR10"].value
        ws_temp["C2"] = ws_source["Z10"].value
        ws_temp["F2"] = ws_source["N10"].value
        ws_temp["I2"] = ws_source["O10"].value
        ws_temp["L2"] = ws_source["Q10"].value
        ws_temp["M2"] = ws_source["P10"].value

        # ------------------------------------------
        # PEMETAAN 3: Pemetaan Kolom Banyak Baris
        # ------------------------------------------
        col_mapping = {
            'AD': 'G', 'AE': 'H', 'AF': 'I', 'AG': 'J',
            'AH': 'K', 'AI': 'L', 'AJ': 'M', 'J': 'U',
            'K': 'V', 'AS': 'W', 'AU': 'Y', 'AV': 'Z'
        }

        max_row = ws_source.max_row
        src_row = 10
        tgt_row = 6
        rows_copied = 0

        # Looping dari baris ke-10 di file sumber ke baris ke-6 di Template
        for r in range(src_row, max_row + 1):
            # Cek apakah baris sumber sudah kosong (untuk stop loop jika data habis)
            is_empty = all(ws_source[f"{src_col}{r}"].value is None for src_col in col_mapping.keys())

            if is_empty and rows_copied > 0:
                if all(ws_source[f"{src_col}{r+1}"].value is None for src_col in col_mapping.keys()):
                    break

            # Menyalin data berdasarkan mapping
            for src_col, tgt_col in col_mapping.items():
                ws_temp[f"{tgt_col}{tgt_row}"].value = ws_source[f"{src_col}{r}"].value

            tgt_row += 1
            rows_copied += 1

        # ------------------------------------------
        # Simpan & Download untuk masing-masing Sheet
        # ------------------------------------------
        # Membersihkan nama file agar tidak ada karakter terlarang (misal ada spasi diubah jadi underscore)
        safe_sheet_name = str(sheet_name).replace(" ", "_").replace("/", "_")
        output_file = f"UPDATED_TEMPLATE_{safe_sheet_name}.xlsx"

        wb_temp.save(output_file)
        print(f"Berhasil! {rows_copied} baris data disalin dari sheet '{sheet_name}'.")
        print(f"File disimpan sebagai: {output_file}\n")

        # Mengunduh file hasil secara otomatis
        files.download(output_file)

    print("Semua sheet telah selesai diproses dan diunduh!")

except Exception as e:
    print(f"\nTerjadi kesalahan: {e}")